name: Format Nix Files with Alejandra

on: 
  push: 
    branches: [ "*" ]
  pull_request:

jobs:
  auto-format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v25

      - name: Run Alejandra formatter check
        run: |
          nix run nixpkgs#alejandra -- .

      - name: Push back changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with: 
          commit_message: "format: format nix files"
