name: Autoformat Files 

on: 
  push: 
    branches: [ "*" ]
    paths: 
      - '**.nix'
      - '**.sh'
  pull_request:

jobs:
  auto-format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup nix
        uses: cachix/install-nix-action@v25

      - name: Install shfmt
        run: |
          sudo apt-get update
          sudo apt-get install -y shfmt

      - name: Run alejandra 
        run: |
          nix run nixpkgs#alejandra -- .

      - name: Run shfmt
        run: |
          shfmt -w -i 2 -ci -sr .

      - name: Push back changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with: 
          commit_message: "format: format files"
